version: '3.8'

services:
  bot:
    build: .
    container_name: flower-shop-bot
    restart: always
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
