version: '3.8'

services:
  bot:
    image: ghcr.io/alekenov/flower_shop_bot:latest
    container_name: flower-shop-bot
    restart: always
    environment:
      - SUPABASE_URL=https://dkohweivbdwweyvyvcbc.supabase.co
      - SUPABASE_HOST=aws-0-eu-central-1.pooler.supabase.com
      - SUPABASE_PORT=6543
      - SUPABASE_DATABASE=postgres
      - SUPABASE_USER=postgres.dkohweivbdwweyvyvcbc
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
