name: Deploy Python Bot

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DOCKER_IMAGE: ghcr.io/${{ github.repository }}
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:latest
          build-args: |
            SUPABASE_URL=https://dkohweivbdwweyvyvcbc.supabase.co
            SUPABASE_SERVICE_ROLE=${{ secrets.SUPABASE_SERVICE_ROLE }}
            SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}
            TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}
            OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
            GOOGLE_SERVICE_ACCOUNT=${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
            SUPABASE_HOST=aws-0-eu-central-1.pooler.supabase.com
            SUPABASE_PORT=6543
            SUPABASE_DATABASE=postgres
            SUPABASE_USER=postgres.dkohweivbdwweyvyvcbc
            SUPABASE_PASSWORD=${{ secrets.SUPABASE_DB_PASSWORD }}

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: flower-shop-bot
          region: europe-west1
          image: ${{ env.DOCKER_IMAGE }}:latest
          env_vars: |
            SUPABASE_URL=https://dkohweivbdwweyvyvcbc.supabase.co
            SUPABASE_HOST=aws-0-eu-central-1.pooler.supabase.com
            SUPABASE_PORT=6543
            SUPABASE_DATABASE=postgres
            SUPABASE_USER=postgres.dkohweivbdwweyvyvcbc
          secrets: |
            SUPABASE_SERVICE_ROLE=${{ secrets.SUPABASE_SERVICE_ROLE }}
            SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}
            TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}
            OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
            GOOGLE_SERVICE_ACCOUNT=${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
            SUPABASE_PASSWORD=${{ secrets.SUPABASE_DB_PASSWORD }}
